name: Build and Test TinyTP

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2019, macos-12 ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

      - name: Build
        run: |
          cmake --build build --config Debug

      - name: Test
        run: |
          ctest -C Debug --test-dir build --rerun-failed --output-on-failure

      - name: Setup python
        uses: actions/setup-python@v4
        if: contains(matrix.os, 'ubuntu')
        with:
          python-version: '3.10'

      - name: Upload code coverage to coveralls
        if: contains(matrix.os, 'ubuntu')
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install --upgrade pip setuptools cpp-coveralls
          coveralls --root . --build-root build -E ".*/_deps/.*" -E ".*/external/.*" -E ".*/usr/include/.*" -E ".*CMakeFiles.*"