name: Build and Test TinyTP

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2019, macos-12 ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -S. -Bbuild

      - name: Build
        run: |
          cmake --build build --config Debug

      - name: Test
        run: |
          cd build
          ctest -C Debug --output-on-failure --verbose
          